## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
import numpy.random
array = numpy.random.randint(1,10,10)
b = np.where((array > 3) & (array <= 8))
array[b]*=-1
print(array)

[-7 -7  9  9  9 -6  3 -5  3  1]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
arr = numpy.random.randint(1,10,10)
arr[np.where(arr == arr.max())] = 0
print(arr)

[0 0 0 4 4 2 5 4 3 6]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
arr = np.array([[7, 4, 3], [9, 8, 6]]) #двумерный массив

cart = np.array(np.meshgrid(arr, arr)).T.reshape(-1,2)

print(cart)

[[7 7]
 [7 4]
 [7 3]
 [7 9]
 [7 8]
 [7 6]
 [4 7]
 [4 4]
 [4 3]
 [4 9]
 [4 8]
 [4 6]
 [3 7]
 [3 4]
 [3 3]
 [3 9]
 [3 8]
 [3 6]
 [9 7]
 [9 4]
 [9 3]
 [9 9]
 [9 8]
 [9 6]
 [8 7]
 [8 4]
 [8 3]
 [8 9]
 [8 8]
 [8 6]
 [6 7]
 [6 4]
 [6 3]
 [6 9]
 [6 8]
 [6 6]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
a = np.random.randint(1,9,(8,3))
b = np.random.randint(1,9,(2,2))
c = (a[..., np.newaxis, np.newaxis] == b)
d = (c.sum(axis=(1,2,3)) >= b.shape[1]).nonzero()[0]
print(d)

[0 2 4 5 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
a = np.random.randint(1,9,(10,3))
b = np.logical_and.reduce(a[:,1:] == a[:,:-1], axis=1)
c = a[~b]
print(c)

[[2 7 3]
 [5 6 6]
 [3 5 5]
 [7 4 5]
 [3 5 7]
 [4 2 6]
 [7 5 4]
 [4 7 8]
 [8 8 4]
 [3 4 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
arr = np.random.randint(1, 9, size=(2, 8))

new_array = [tuple(row) for row in arr]

unique_num = np.unique(new_array, axis=0)

print(unique_num)

[[5 5 4 8 7 7 2 7]
 [5 5 8 1 6 6 6 4]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [25]:
# 1 способ 
def diagonal_product_numpy(matrix):
    diagonal_elements = np.diagonal(matrix) # Получить диагональные элементы как одномерный массив
    non_zero_diagonal_elements = diagonal_elements[diagonal_elements != 0] # Отфильтровать ненулевые элементы
    product = np.prod(non_zero_diagonal_elements) # Вычислить произведение ненулевых элементов
    return product

# Пример
matrix = np.array([
    [0, 7, 0],
    [0, 8, 0],
    [1, 0, 0]
])

result = diagonal_product_numpy(matrix)
print("Произведение ненулевых элементов на диагонали:", result)

Произведение ненулевых элементов на диагонали: 8


In [9]:
# 2 способ
def diagonal_product(matrix):
    if not matrix:
        return None             # Проверка что матрица не пустая
    rows = len(matrix)          # Размеры матрицы
    cols = len(matrix[0])
    product = 1                 # Для хранения произведения
    for i in range(min(rows, cols)):    # Итерация по диагонали и умножения ненулевых значений
        if matrix[i][i] != 0:
            product *= matrix[i][i]
    
    return product

# Пример
matrix = [
    [5, 0, 0],
    [0, 8, 0],
    [0, 0, 9]
]

result = diagonal_product(matrix)
print("Произведение ненулевых элементов на диагонали:", result)

Произведение ненулевых элементов на диагонали: 360


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
# 1 способ

def are_multisets_equal(x, y):
    # Отсортировать векторы
    sorted_x = np.sort(x)
    sorted_y = np.sort(y)
    # Сравнить отсортированные векторы
    return np.array_equal(sorted_x, sorted_y)

# Пример
x = np.array([1, 5, 7, 9])
y = np.array([4, 3, 2, 7])

result = are_multisets_equal(x, y)
print(result)

False


In [11]:
# 2 способ

def are_multisets_equal(x, y):
    # Отсортировать векторы
    sorted_x = sorted(x)
    sorted_y = sorted(y)
    # Сравнить отсортированные векторы
    return sorted_x == sorted_y

# Пример
x = [1, 5, 7, 9]
y = [4, 3, 2, 7]

result = are_multisets_equal(x, y)
print(result)

False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [12]:
# 1 способ 

def max_after_zero(x):
    # Найти индексы элементов, равных 0
    zero_indices = np.where(x == 0)[0]
    
    # Получить индексы элементов после нулей
    indices_after_zero = zero_indices + 1
    
    # Отфильтровать индексы, чтобы они оставались в пределах массива
    indices_after_zero = indices_after_zero[indices_after_zero < len(x)]
    
    # Найти максимальный элемент среди элементов после нулей
    max_after_zero_value = np.max(x[indices_after_zero])
    
    return max_after_zero_value

# Пример
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
result = max_after_zero(x)
print("Максимальный элемент после нуля:", result)

Максимальный элемент после нуля: 5


In [13]:
# 2 способ

def max_after_zero(x):
    # Найти индексы элементов, равных 0
    zero_indices = [i for i, value in enumerate(x) if value == 0]
    
    # Получить индексы элементов после нулей
    indices_after_zero = [index + 1 for index in zero_indices if index + 1 < len(x)]
    
    # Найти максимальный элемент среди элементов после нулей
    max_after_zero_value = max(x[index] for index in indices_after_zero)
    
    return max_after_zero_value

# Пример
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
result = max_after_zero(x)
print("Максимальный элемент после нуля:", result)

Максимальный элемент после нуля: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [26]:
# 1 способ

def run_length_encoding(x):
    # Инициализация переменных
    unique_values, counts = np.unique(x, return_counts=True)
    
    # Возвращение кортежа из двух векторов
    return unique_values, counts

# Пример
x = np.array([5, 7, 6, 3, 2, 3, 5])
result = run_length_encoding(x)

print("Входной вектор:", x)
print("Закодированный результат:")
print("Уникальные значения:", result[0])
print("Количество повторений:", result[1])

Входной вектор: [5 7 6 3 2 3 5]
Закодированный результат:
Уникальные значения: [2 3 5 6 7]
Количество повторений: [1 2 2 1 1]


In [27]:
# 2 способ

def run_length_encoding(x):
    unique_values = []
    counts = []

    # Iterating through the input list
    i = 0
    while i < len(x):
        # Current element
        current_value = x[i]

        # Count occurrences of the current element
        count = 1
        while i + 1 < len(x) and x[i] == x[i + 1]:
            count += 1
            i += 1

        # Append unique value and count to lists
        unique_values.append(current_value)
        counts.append(count)

        # Move to the next element
        i += 1

    return unique_values, counts

# Example
x = [5, 7, 6, 3, 2, 3, 5]
result = run_length_encoding(x)

print("Входной вектор:", x)
print("Закодированный результат:")
print("Уникальные значения:", result[0])
print("Количество повторений:", result[1])

Входной вектор: [5, 7, 6, 3, 2, 3, 5]
Закодированный результат:
Уникальные значения: [5, 7, 6, 3, 2, 3, 5]
Количество повторений: [1, 1, 1, 1, 1, 1, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [28]:
# 1 способ

def euclidean_distance_matrix(X, Y):
    # Разница между объектами по каждой координате
    diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
    
    # Возведение в квадрат каждой разницы и суммирование по координатам
    distances = np.sqrt(np.sum(diff**2, axis=-1))
    
    return distances

# Пример
X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[7, 8], [9, 10]])

# Вычисление матрицы евклидовых расстояний
result_custom = euclidean_distance_matrix(X, Y)

print("Матрица евклидовых расстояний (собственная реализация):")
print(result_custom)

Матрица евклидовых расстояний (собственная реализация):
[[ 8.48528137 11.3137085 ]
 [ 5.65685425  8.48528137]
 [ 2.82842712  5.65685425]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [16]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [17]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [18]:
# your code

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [19]:
# your code

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [20]:
# your code

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [21]:
# your code

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [22]:
# your code

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [23]:
# your code

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [24]:
# your code